<?php

function athex_customizations_views_plugins_exposed_form_alter(&$form) {
	// \Drupal::messenger()->addStatus(print_r($form));
}

function athex_customizations_views_pre_view($view) { // by value??
	// improve VBO controls
	// $exposed_input = $view->getExposedInput();



	// override options
	$MAP = [
		'year' => function() {
			$years = [];
			for ($i = 0; $i < 5; $i++) {
				$year = date('Y') - $i;
				$years[] = [
					'title' => $year,
					'operator' => '=',
					'value' => $year
				];
			}
			return $years;
		}
	];

	foreach ($MAP as $key => $value)
		$MAP[$key] = $value();

	$filters = $view->display_handler->getOption('filters');

	foreach ($filters as $key => &$filter) {
		$ginfo = $filter['group_info'] ?? [];
		$mapping = @$MAP[$ginfo['identifier']];

		if (!isset($mapping)) continue;

		$filter['group_info']['group_items'] = $mapping;
	}

	$view->display_handler->overrideOption('filters', $filters);
}
