<?php
use Symfony\Component\Routing\Route;
use Drupal\Core\Routing\RouteProviderInterface;

/*
$route_provider = \Drupal::service('router.route_provider');
$all_routes = $route_provider->getAllRoutes();

foreach ($all_routes as $route_name => $route) {
	if (strpos($route_name, 'athex_d_products') !== FALSE) {
		// This is one of your custom routes.
		print_r($route_name . "\n");
		// You can also inspect the $route object for more details.
	}
}


*/








function athex_d_products_theme($existing, $type, $theme, $path) {
	return [
		'product_search' => [
			'variables' => [
				'page_title' => null,
				'search_form' => null,
				'table' => null,
				'pager' => null
			]
		],
		'product_hero' => [
			'variables' => [
				'product_name' => null,
				'cover_img_url' => null,
				'logo_url' => null,
				'ticker' => null
			]
		],
		'product_ticker' => [
			'variables' => []
		]
	];
}
