<?php

function athex_d_products_theme($existing, $type, $theme, $path) {
	return [
		'stock_search' => [
			'variables' => [
				'search_form' => null,
				'table' => null,
				'pager' => null
			]
		],
		'stock_hero' => [
			'variables' => [
				'stock_name' => null,
				'cover_img_url' => null,
				'logo_url' => null,
				'ticker' => null
			]
		],
		'stock_ticker' => [
			'variables' => []
		]
	];
}
