<?php

/**
 * @file
 * Install file to check the requirements.
 */

/**
 * Implements hook_requirements().
 */
function download_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\PclZip')) {
      $requirements['pclzip_library'] = [
        'description' => t('Download requires the pclzip/pclzip library.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}
